---
# XXX For ansible 2.1.1.0, iptables can't find our rules
- name: block remote access to iRODS
  hosts: irods
  become: true
  gather_facts: true
  tasks:
    - name: determine the name of the iptables INPUT chain
      shell: |
        sed --quiet 's/^-A \(.*INPUT\) .*-m state --state NEW -m tcp .*--dport 1247 .*$/\1/p' \
            /etc/sysconfig/iptables \
          | head --lines 1
      args:
        warn: false
      register: sed
      changed_when: false

    - name: ensure resource servers can still access IES
      lineinfile:
        dest: /etc/sysconfig/iptables
        insertbefore: -A {{ sed.stdout }} .*-m state --state NEW -m tcp .*--dport 1247
        line: -A {{ sed.stdout }} -m state --state NEW -m tcp -p tcp -s {{ lookup('dig', item) }} --dport 1247 -j ACCEPT
      with_items: "{{ groups['irods'] }}"
      register: rs_access

    - name: block port 1247 for everyone else
      lineinfile:
        dest: /etc/sysconfig/iptables
        insertbefore: -A {{ sed.stdout }} .*-m state --state NEW -m tcp .*--dport 1247
        line: -A {{ sed.stdout }} -m state --state NEW -m tcp -p tcp --dport 1247 -j REJECT
      register: block_rest

    - name: open port 1248 
      lineinfile:
        dest: /etc/sysconfig/iptables
        insertafter: -A {{ sed.stdout }} .*-m state --state NEW -m tcp .*--dport 1247
        line: -A {{ sed.stdout }} -m state --state NEW -m tcp -p tcp --dport 1248 -j ACCEPT
      register: access_1248
 
    - name: reload iptables
      service:
        name: iptables
        state: restarted  # XXX reloaded fails
      when: rs_access|changed or block_rest|changed or access_1248|changed
