---
- name: reboot servers
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: reboot
      command: /sbin/reboot
      async: 0
      poll: 0
      
    - name: wait for server to stop
      become: false
      local_action: wait_for host={{ ansible_host }} port={{ ansible_ssh_port }} state=stopped

    - name: verify server up
      become: false
      local_action: wait_for host={{ ansible_host }} port={{ ansible_ssh_port }} state=started

